[env]
CARGO_MAKE_EXTEND_WORKSPACE_MAKEFILE = true
# project vars
HTTP_SERVER_API_KEY = "override-secret-here"
# TODO: 
SERVER_HTTP_SERVER_API_KEY = "override-secret-here-NEW-ONE"
HTTP_SERVER_URI = "0.0.0.0:8643"
LOGFILE_LEVEL = "DEBUG"
LOG_LEVEL = "DEBUG"
RUST_LOG = "trace,actix_server=trace,actix_web=trace"
# aes-gcm: when targeting modern x86/x86_64 CPUs, use the following RUSTFLAGS to take advantage of high performance AES-NI and CLMUL CPU intrinsics
# RUSTFLAGS = "-Ctarget-cpu=sandybridge -Ctarget-feature=+aes,+sse2,+sse4.1,+ssse3"

[tasks.format]
command = "cargo"
args = ["fmt", "--", "--emit=files"]
install_crate = "rustfmt"

[tasks.clean]
command = "cargo"
args = ["clean"]

[tasks.build]
command = "cargo"
args = ["build"]
# dependencies = ["clean"]

[tasks.release]
command = "cargo"
args = ["build", "-r"]
# dependencies = ["clean"]
# workspace = true

[tasks.test]
command = "cargo"
args = ["test"]
dependencies = ["clean"]

[tasks.run]
command = "cargo"
args = ["run"]

[tasks.watch]
command = "cargo"
args = ["watch", "-x", "run"]
dependencies = ["clean"]

# stub for args
[tasks.echo]
args = ["${@}"]
command = "echo"

[tasks.my-flow]
dependencies = [
  "format",
  "build",
  "test",
]
