# Default settings

# port = 0
run_mode = "development"

[server]
# leave it for env
# uri = "0.0.0.0:8643"
enable_https = true
api_key = "override-secret-here"

[certificate]
config_path = "./config/ssl"
file_name_cert = "cert.pem"
file_name_key = "key.pem"

[log]
log_file_path = "/tmp/server-starter.log"
log_file_level = "WARN"
log_level = "WARN"

# [database]
# debug = false
# hostname = "localhost"
# name = "caster_rust"
# password = "caster"
# port = 1701
# url = "postgresql://caster:caster@localhost:1701/caster_rust"
# username = "caster"

# [database.pool]

# [redis]
# url = "localhost:6379"

# [auth]
# audience = "localhost"
# url = "https://kuartzo.com:444"

# [auth.client]

# [auth.test.user]

# [auth.test.alt]
