# Default settings

port = 0
run_mode = "development"

[server]
http_server_uri = "0.0.0.0:8643"
http_server_enable_https = true
http_server_api_key = "override-secret-here-toml"
value_b_c =  "override-secret-here-toml"

[certificate]
# config_path = "./config/ssl"
# file_name_cert = "cert.pem"
# file_name_key = "key.pem"

[log]
# log_file_path = "/tmp/server-starter.log"
# log_file_level = "WARN"
# log_level = "WARN"

# [database]
# debug = false
# hostname = "localhost"
# name = "caster_rust"
# password = "caster"
# port = 1701
# url = "postgresql://caster:caster@localhost:1701/caster_rust"
# username = "caster"

# [database.pool]

# [redis]
# url = "localhost:6379"

# [auth]
# audience = "localhost"
# url = "https://kuartzo.com:444"

# [auth.client]

# [auth.test.user]

# [auth.test.alt]
